---
- name: Ensure group for prometheus user exists
  group:
    name: '{{ nextcloud_exporter_group }}'
    state: present
  become: True

- name: Add prometheus user
  user:
    name: '{{ nextcloud_exporter_user }}'
    home: '{{ nextcloud_exporter_user_home }}'
    group: '{{ nextcloud_exporter_group }}'
    shell: '{{ nextcloud_exporter_user_shell }}'
    state: present
  become: True

- name: Create nextcloud exporter directory
  file:
    path: '{{ nextcloud_exporter_install_path }}'
    owner: '{{ nextcloud_exporter_user }}'
    group: '{{ nextcloud_exporter_group }}'
    mode: 0755
    state: directory
  become: True

- name: Check if nextcloud_exporter already exists
  stat:
    path: '{{ nextcloud_exporter_install_path }}/nextcloud_exporter'
  register: result

- name: Download nextcloud exporter
  get_url:
    url: '{{ nextcloud_exporter_download_url }}'
    dest: '/tmp/nextcloud_exporter.bz2'
  when: not result.stat.exists

- name: Extract nextcloud_exporter.bz2
  shell: 'bunzip2 /tmp/nextcloud_exporter.bz2 -c > {{ nextcloud_exporter_install_path }}/nextcloud_exporter'
  when: not result.stat.exists
  become: True

- name: Set file permission for nextcloud_exporter
  file:
    path: '{{ nextcloud_exporter_install_path }}/nextcloud_exporter'
    owner: '{{ nextcloud_exporter_user }}'
    group: '{{ nextcloud_exporter_group }}'
    mode: 0770
  become: True

- name: Install nextcloud exporter systemd unit file
  template:
    src: 'nextcloud_exporter.service.j2'
    dest: '/etc/systemd/system/nextcloud_exporter.service'
    owner: '{{ nextcloud_exporter_user }}'
    group: '{{ nextcloud_exporter_group }}'
    mode: 0644
  notify:
    - reload systemd_daemon
    - restart nextcloud_exporter
  become: True

- meta: flush_handlers

- name: Check if nextcloud exporter is started
  service:
    name: nextcloud_exporter.service
    state: started
    enabled: yes
