---
- name: reload systemd_daemon
  systemd:
    daemon_reload: yes
  become: True

- name: restart nextcloud_exporter
  service:
    name: nextcloud_exporter
    state: restarted
    enabled: yes
  become: True
